---
networks:
  denv:
    external: true

volumes:
  postgres-data:

services:

# -----------------------------------------------------------------------------

  postgres:
    image: postgres
    container_name: denv-postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/postgres
    networks:
      - denv
    labels:
      - 'traefik.enable=true'
      - 'traefik.profile=denv'
      - 'traefik.http.services.postgres.loadbalancer.server.port=5432'

# -----------------------------------------------------------------------------

